### ISSUE TITLE
ソースコードの可読性の向上

### ISSUE THREAD

**Issue by novum-d** [novum-d/android-engineer-codecheck#1]
本プロジェクトのソースコードはとても読みにくいです。下記のリストを参考に読みやすいように修正してください。

- [x] 命名規約
- [x] ネスト
- [x] インデント
- [x] スペースや改行
- [x] コメントの適切性
- [ ] その他

参考：https://kotlinlang.org/docs/coding-conventions.html

**Comment by HamadaTomoki** [comment]
ktlintを使用して、不要なアンダーバーおよびダウンキャメルケースを改善
https://github.com/pinterest/ktlint

**Comment by HamadaTomoki** [comment]
コメントからドキュメントで自動生成できるdokkaを導入
https://github.com/Kotlin/dokka
