### ISSUE TITLE
ソースコードの安全性の向上 

### ISSUE THREAD

**Issue by novum-d** [novum-d/android-engineer-codecheck#2]
本プロジェクトには安全性の低いがコードたくさんあります。下記のリストを参考に、安全性の低いコードを撲滅し、安全性を高めましょう。

- [x]  非 null 表明演算子
- [x]  強制ダウンキャスト
- [x]  不必要な lateinit 修飾子
- [x]  想定外の null の握り潰し

**Comment by HamadaTomoki** [comment]
context!! を非nullのContextを値として返すrequireContextに変更
https://developer.android.com/kotlin/common-patterns?hl=ja&authuser=1#interop

**Comment by HamadaTomoki** [comment]
Activityは状態を保存する場所ではないので、lastSearchDateをViewModelに移動

以下の箇所を変更
https://github.com/HamadaTomoki/android-engineer-codecheck/blob/d77f383f9cd597525756b7e4fdc81e09f68de9d1/app/src/main/kotlin/jp/co/yumemi/android/codeCheck/TopActivity.kt#L9-L14

**Comment by HamadaTomoki** [comment]
ジェネリクスを正しく指定する(View → TextView)ことでダウンキャストを回避

以下の箇所を変更(インデントも修正)
https://github.com/HamadaTomoki/android-engineer-codecheck/blob/d77f383f9cd597525756b7e4fdc81e09f68de9d1/app/src/main/kotlin/jp/co/yumemi/android/codeCheck/SearchRepositoryFragment.kt#L94-L95
