### ISSUE TITLE
バグを修正

### ISSUE THREAD

**Issue by novum-d** [novum-d/android-engineer-codecheck#3]
本プロジェクトには、至る所にバグが潜んでいます。下記のリストを参考にバグを修正してください。

- [x] レイアウトエラー
- [x] メモリリーク
- [x] パースエラー
- [x] 例外の処理漏れ
- [x] クラッシュ

**Comment by HamadaTomoki** [comment]
DIコンテナにkoinを使用
https://insert-koin.io/docs/quickstart/kotlin

**Comment by HamadaTomoki** [comment]
ViewModelにActivity contextを渡すことはメモリリークの危険性があるため、アンチパターンとされている。
どうしても、必要なときはAndroidViewModelを使用する。
https://developer.android.com/topic/libraries/architecture/viewmodel?gclid=Cj0KCQjwvLOTBhCJARIsACVldV3BMB9FF_tD4NIy3iTRGRgWf6YCBZ-T9DPQ1cjTEpu_8q8mObJBjUYaAmuYEALw_wcB&gclsrc=aw.ds&authuser=1#implement

**Comment by HamadaTomoki** [comment]
レイアウトのデフォルト文字がハードコーディングされていたのでstring resourceに移動。

**Comment by HamadaTomoki** [comment]
json keyの指定が一部、countではなくconutになっていたので修正

**Comment by HamadaTomoki** [comment]
可変文字列リソースで指定する

フォーマットに関してはFormatterで規定されている
http://developer.android.com/reference/java/util/Formatter.html
