### ISSUE TITLE
プログラム構造をリファクタリング 

### ISSUE THREAD

**Issue by novum-d** [novum-d/android-engineer-codecheck#5]
本プロジェクトは様々な原則に違反しています。下記のリストを参考にプログラムをリファクタリングしましょう。

- [x] DRY 原則
- [x] CQS 原則
- [x] 単一責任原則
- [x] インターフェイス分離の原則
- [x] 驚き最小の原則

**Comment by HamadaTomoki** [comment]
- DRY原則
  Don't repeat yourself、コードの重複を避けるための原則。

**Comment by HamadaTomoki** [comment]
- コマンドクエリ分離原則(CQS)
  副作用を最小限に抑えるための原則。
  オブジェクトのメソッドを2つの機能に分け、その両方の機能を兼ね備えてはならない。

  > Query：結果を返し、システムの状態を変更しない(副作用なし)
  > Command：システムの状態を変更し、値を返さない(副作用あり)

**Comment by HamadaTomoki** [comment]
- 単一責任の原則（Single Responsibility Principle）
  個々のモジュール（関数やクラス）は、一つの責任だけを持つべきという原則。1クラスに1アクター。

> アクター :  システムに対して果たす役割が決まったもの

**Comment by HamadaTomoki** [comment]
- インターフェース分離の原則（Interface segregation principle）
  利用しないメソッドの継承を強制させないための原則。不要なメソッドがある場合は、新たにインターフェースを分離して移動させる。
   https://zenn.dev/chida/articles/882aad07effa5c

**Comment by HamadaTomoki** [comment]
- Principle of least astonishment（驚き最小の原則）
  ソフトウェアやユーザーインターフェース、または設計等はユーザーやアクターが期待したり想定しうる動作を行う必要があり、そうでない場合は見直す必要があることを示す原則。
  https://zenn.dev/tak_uchida/articles/d862a077954627#principle-of-least-astonishment%EF%BC%88%E9%A9%9A%E3%81%8D%E6%9C%80%E5%B0%8F%E3%81%AE%E5%8E%9F%E5%89%87%EF%BC%89
