### ISSUE TITLE
アーキテクチャを適用

### ISSUE THREAD

**Issue by novum-d** [novum-d/android-engineer-codecheck#6]
最近巷では MVC や MVVM などの GUI アーキテクチャから、Redux や VIPER などのアプリアーキテクチャまで様々なアーキテクチャが話題になっています。どれでもいいので本プロジェクトを自分の慣れたアーキテクチャに修正してください。

※本課題は #4 の上位互換です。

**Comment by HamadaTomoki** [comment]
MVVM + Repositoryパターン アーキテクチャを適用

<img width="632" alt="スクリーンショット 2022-05-02 16 13 54" src="https://user-images.githubusercontent.com/68803158/166197902-8a90344d-2c5c-45f8-82ca-6742dc07b911.png">
