### ISSUE TITLE
UI をブラッシュアップ

### ISSUE THREAD

**Issue by novum-d** [novum-d/android-engineer-codecheck#8]
本アプリの UI は極めてシンプルです。これでも特に問題はありませんが、やはりいまいち映えないです。**使いやすさが損なわれない**前提で、UI をブラッシュアップしてください。方向性（エレガント、ゴージャス、モダン等）は問いません。また Jetpack Compose の導入も OK です。

**Comment by HamadaTomoki** [comment]
既存UIをJetpack Composeに移行する
https://developer.android.com/jetpack/compose/interop/compose-in-existing-ui?hl=ja
